mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

"""
In this file we will set our models, basically what data we are expecting/need and the same will be reflected into the db. 

We divide them by Class and then using the models.Model, and then we set the variables which will be fields in the database (with specifying the data type of the field)

Each class creates a table in the database

we also create relationship between different classes by using a foreignkey

Every time we make changes to models,
- Change your models (in models.py).
- Run python manage.py makemigrations to create migrations for those changes
 -Run python manage.py migrate to apply those changes to the database. 
"""

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404

from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]

    context = {
        "latest_question_list": latest_question_list
    }

    return render(request(context, "polls/index.html"))

def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    

    return render(request, "polls/detail.html", {"question": question})

def results(request, question_id):
    response = f"You're looking at the result of question {question_id}"
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse(f"You're voting on question {question_id}")

polls/templates/polls/detail.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Detail</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>
  </body>
</html>

polls/templates/polls/index.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}/">{{question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
  </body>
</html>